//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

namespace EkiEVS.Schema
{

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class v
	{

		private levik_tyyp lField;

		private bool lFieldSpecified;

		private v_tyyp valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public levik_tyyp l
		{
			get
			{
				return this.lField;
			}
			set
			{
				this.lField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lSpecified
		{
			get
			{
				return this.lFieldSpecified;
			}
			set
			{
				this.lFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public v_tyyp Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum levik_tyyp
	{

		/// <remarks/>
		ka,

		/// <remarks/>
		hrl,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum v_tyyp
	{

		/// <remarks/>
		aiand,

		/// <remarks/>
		aj,

		/// <remarks/>
		anat,

		/// <remarks/>
		antr,

		/// <remarks/>
		arheol,

		/// <remarks/>
		arhit,

		/// <remarks/>
		astr,

		/// <remarks/>
		aut,

		/// <remarks/>
		bibl,

		/// <remarks/>
		biol,

		/// <remarks/>
		bot,

		/// <remarks/>
		ehit,

		/// <remarks/>
		el,

		/// <remarks/>
		etn,

		/// <remarks/>
		farm,

		/// <remarks/>
		film,

		/// <remarks/>
		filos,

		/// <remarks/>
		folkl,

		/// <remarks/>
		fot,

		/// <remarks/>
		füsiol,

		/// <remarks/>
		füüs,

		/// <remarks/>
		geod,

		/// <remarks/>
		geogr,

		/// <remarks/>
		geol,

		/// <remarks/>
		hüdr,

		/// <remarks/>
		info,

		/// <remarks/>
		jah,

		/// <remarks/>
		jur,

		/// <remarks/>
		kal,

		/// <remarks/>
		keem,

		/// <remarks/>
		ker,

		/// <remarks/>
		kirikl,

		/// <remarks/>
		kirj,

		/// <remarks/>
		kul,

		/// <remarks/>
		kunst,

		/// <remarks/>
		lenn,

		/// <remarks/>
		lgv,

		/// <remarks/>
		loog,

		/// <remarks/>
		maj,

		/// <remarks/>
		mat,

		/// <remarks/>
		med,

		/// <remarks/>
		meh,

		/// <remarks/>
		mer,

		/// <remarks/>
		mes,

		/// <remarks/>
		meteor,

		/// <remarks/>
		mets,

		/// <remarks/>
		min,

		/// <remarks/>
		mull,

		/// <remarks/>
		muus,

		/// <remarks/>
		mäend,

		/// <remarks/>
		müt,

		/// <remarks/>
		nahat,

		/// <remarks/>
		paberit,

		/// <remarks/>
		paleont,

		/// <remarks/>
		pat,

		/// <remarks/>
		ped,

		/// <remarks/>
		pol,

		/// <remarks/>
		psühh,

		/// <remarks/>
		puidut,

		/// <remarks/>
		põll,

		/// <remarks/>
		raad,

		/// <remarks/>
		raudt,

		/// <remarks/>
		side,

		/// <remarks/>
		sotsiol,

		/// <remarks/>
		sport,

		/// <remarks/>
		stat,

		/// <remarks/>
		sõj,

		/// <remarks/>
		zool,

		/// <remarks/>
		teater,

		/// <remarks/>
		teed,

		/// <remarks/>
		tehn,

		/// <remarks/>
		tekst,

		/// <remarks/>
		trük,

		/// <remarks/>
		vet,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class s
	{

		private levik_tyyp lField;

		private bool lFieldSpecified;

		private s_tyyp valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public levik_tyyp l
		{
			get
			{
				return this.lField;
			}
			set
			{
				this.lField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lSpecified
		{
			get
			{
				return this.lFieldSpecified;
			}
			set
			{
				this.lFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public s_tyyp Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum s_tyyp
	{

		/// <remarks/>
		arg,

		/// <remarks/>
		dem,

		/// <remarks/>
		hellitl,

		/// <remarks/>
		hlv,

		/// <remarks/>
		hrv,

		/// <remarks/>
		iroon,

		/// <remarks/>
		kõnek,

		/// <remarks/>
		[System.Xml.Serialization.XmlEnumAttribute("kõnek ka piltl")]
		kõnekkapiltl,

		/// <remarks/>
		kõrgst,

		/// <remarks/>
		liter,

		/// <remarks/>
		lstk,

		/// <remarks/>
		luulek,

		/// <remarks/>
		madalk,

		/// <remarks/>
		murd,

		/// <remarks/>
		nlj,

		/// <remarks/>
		nõuk,

		/// <remarks/>
		piltl,

		/// <remarks/>
		rhvk,

		/// <remarks/>
		van,

		/// <remarks/>
		vulg,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	[System.Xml.Serialization.XmlRootAttribute("vgsugu", Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public enum sugu_tyyp
	{

		/// <remarks/>
		м,

		/// <remarks/>
		ж,

		/// <remarks/>
		с,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class m
	{

		private string iField;

		private msliik_tyyp liikField;

		private bool liikFieldSpecified;

		private string oField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "positiveInteger")]
		public string i
		{
			get
			{
				return this.iField;
			}
			set
			{
				this.iField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public msliik_tyyp liik
		{
			get
			{
				return this.liikField;
			}
			set
			{
				this.liikField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool liikSpecified
		{
			get
			{
				return this.liikFieldSpecified;
			}
			set
			{
				this.liikFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public string O
		{
			get
			{
				return this.oField;
			}
			set
			{
				this.oField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum msliik_tyyp
	{

		/// <remarks/>
		z,

		/// <remarks/>
		p,

		/// <remarks/>
		y,

		/// <remarks/>
		f,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class mg
	{

		private m mField;

		private string egrField;

		private string hldField;

		private string vkField;

		/// <remarks/>
		public m m
		{
			get
			{
				return this.mField;
			}
			set
			{
				this.mField = value;
			}
		}

		/// <remarks/>
		public string egr
		{
			get
			{
				return this.egrField;
			}
			set
			{
				this.egrField = value;
			}
		}

		/// <remarks/>
		public string hld
		{
			get
			{
				return this.hldField;
			}
			set
			{
				this.hldField = value;
			}
		}

		/// <remarks/>
		public string vk
		{
			get
			{
				return this.vkField;
			}
			set
			{
				this.vkField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class evg
	{

		private string vkField;

		private string evField;

		/// <remarks/>
		public string vk
		{
			get
			{
				return this.vkField;
			}
			set
			{
				this.vkField = value;
			}
		}

		/// <remarks/>
		public string ev
		{
			get
			{
				return this.evField;
			}
			set
			{
				this.evField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class grg
	{

		private string mvlField;

		private string mvField;

		private evg evgField;

		private string slyField;

		private string mtField;

		private string erField;

		private string rkField;

		private string gkiField;

		/// <remarks/>
		public string mvl
		{
			get
			{
				return this.mvlField;
			}
			set
			{
				this.mvlField = value;
			}
		}

		/// <remarks/>
		public string mv
		{
			get
			{
				return this.mvField;
			}
			set
			{
				this.mvField = value;
			}
		}

		/// <remarks/>
		public evg evg
		{
			get
			{
				return this.evgField;
			}
			set
			{
				this.evgField = value;
			}
		}

		/// <remarks/>
		public string sly
		{
			get
			{
				return this.slyField;
			}
			set
			{
				this.slyField = value;
			}
		}

		/// <remarks/>
		public string mt
		{
			get
			{
				return this.mtField;
			}
			set
			{
				this.mtField = value;
			}
		}

		/// <remarks/>
		public string er
		{
			get
			{
				return this.erField;
			}
			set
			{
				this.erField = value;
			}
		}

		/// <remarks/>
		public string rk
		{
			get
			{
				return this.rkField;
			}
			set
			{
				this.rkField = value;
			}
		}

		/// <remarks/>
		public string gki
		{
			get
			{
				return this.gkiField;
			}
			set
			{
				this.gkiField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class mvt
	{

		private msviiteliik_tyyp mvtlField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public msviiteliik_tyyp mvtl
		{
			get
			{
				return this.mvtlField;
			}
			set
			{
				this.mvtlField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum msviiteliik_tyyp
	{

		/// <remarks/>
		gr,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class P
	{

		private mg mgField;

		private grg[] grgField;

		private v[] vField;

		private s[] sField;

		private mvt[] mvtField;

		/// <remarks/>
		public mg mg
		{
			get
			{
				return this.mgField;
			}
			set
			{
				this.mgField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("grg")]
		public grg[] grg
		{
			get
			{
				return this.grgField;
			}
			set
			{
				this.grgField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("mvt")]
		public mvt[] mvt
		{
			get
			{
				return this.mvtField;
			}
			set
			{
				this.mvtField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class d
	{

		private string langField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class dg
	{

		private v[] vField;

		private s[] sField;

		private d[] dField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("d")]
		public d[] d
		{
			get
			{
				return this.dField;
			}
			set
			{
				this.dField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class x
	{

		private string[] xrField;

		private string[] textField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("xr")]
		public string[] xr
		{
			get
			{
				return this.xrField;
			}
			set
			{
				this.xrField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vgarv
	{

		private string langField;

		private arv_tyyp valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public arv_tyyp Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum arv_tyyp
	{

		/// <remarks/>
		pl,

		/// <remarks/>
		plt,

		/// <remarks/>
		sgt,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vgerprag
	{

		private string langField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vgergrp
	{

		private string vgervkField;

		private vgerprag vgerpragField;

		private string vgervormField;

		/// <remarks/>
		public string vgervk
		{
			get
			{
				return this.vgervkField;
			}
			set
			{
				this.vgervkField = value;
			}
		}

		/// <remarks/>
		public vgerprag vgerprag
		{
			get
			{
				return this.vgerpragField;
			}
			set
			{
				this.vgerpragField = value;
			}
		}

		/// <remarks/>
		public string vgervorm
		{
			get
			{
				return this.vgervormField;
			}
			set
			{
				this.vgervormField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vg
	{

		private string vgvormidField;

		private vgergrp[] vgergrpField;

		private string vgpragField;

		private vgarv vgarvField;

		private sugu_tyyp[] vgsuguField;

		/// <remarks/>
		public string vgvormid
		{
			get
			{
				return this.vgvormidField;
			}
			set
			{
				this.vgvormidField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("vgergrp")]
		public vgergrp[] vgergrp
		{
			get
			{
				return this.vgergrpField;
			}
			set
			{
				this.vgergrpField = value;
			}
		}

		/// <remarks/>
		public string vgprag
		{
			get
			{
				return this.vgpragField;
			}
			set
			{
				this.vgpragField = value;
			}
		}

		/// <remarks/>
		public vgarv vgarv
		{
			get
			{
				return this.vgarvField;
			}
			set
			{
				this.vgarvField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("vgsugu")]
		public sugu_tyyp[] vgsugu
		{
			get
			{
				return this.vgsuguField;
			}
			set
			{
				this.vgsuguField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class ag
	{

		private string agvormidField;

		/// <remarks/>
		public string agvormid
		{
			get
			{
				return this.agvormidField;
			}
			set
			{
				this.agvormidField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vvald
	{

		private string langField;

		private levik_tyyp lField;

		private bool lFieldSpecified;

		private v_tyyp valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public levik_tyyp l
		{
			get
			{
				return this.lField;
			}
			set
			{
				this.lField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lSpecified
		{
			get
			{
				return this.lFieldSpecified;
			}
			set
			{
				this.lFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public v_tyyp Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class vstiil
	{

		private string langField;

		private levik_tyyp lField;

		private bool lFieldSpecified;

		private s_tyyp valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public levik_tyyp l
		{
			get
			{
				return this.lField;
			}
			set
			{
				this.lField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool lSpecified
		{
			get
			{
				return this.lFieldSpecified;
			}
			set
			{
				this.lFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public s_tyyp Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class xg
	{

		private x xField;

		private string vstgtField;

		private string vstvkField;

		private vg vgField;

		private string aspvstField;

		private string aspgtField;

		private ag agField;

		private string[] vrekField;

		private vvald[] vvaldField;

		private vstiil[] vstiilField;

		/// <remarks/>
		public x x
		{
			get
			{
				return this.xField;
			}
			set
			{
				this.xField = value;
			}
		}

		/// <remarks/>
		public string vstgt
		{
			get
			{
				return this.vstgtField;
			}
			set
			{
				this.vstgtField = value;
			}
		}

		/// <remarks/>
		public string vstvk
		{
			get
			{
				return this.vstvkField;
			}
			set
			{
				this.vstvkField = value;
			}
		}

		/// <remarks/>
		public vg vg
		{
			get
			{
				return this.vgField;
			}
			set
			{
				this.vgField = value;
			}
		}

		/// <remarks/>
		public string aspvst
		{
			get
			{
				return this.aspvstField;
			}
			set
			{
				this.aspvstField = value;
			}
		}

		/// <remarks/>
		public string aspgt
		{
			get
			{
				return this.aspgtField;
			}
			set
			{
				this.aspgtField = value;
			}
		}

		/// <remarks/>
		public ag ag
		{
			get
			{
				return this.agField;
			}
			set
			{
				this.agField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("vrek")]
		public string[] vrek
		{
			get
			{
				return this.vrekField;
			}
			set
			{
				this.vrekField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("vvald")]
		public vvald[] vvald
		{
			get
			{
				return this.vvaldField;
			}
			set
			{
				this.vvaldField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("vstiil")]
		public vstiil[] vstiil
		{
			get
			{
				return this.vstiilField;
			}
			set
			{
				this.vstiilField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class xp
	{

		private xg[] xgField;

		private string langField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("xg")]
		public xg[] xg
		{
			get
			{
				return this.xgField;
			}
			set
			{
				this.xgField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class tg
	{

		private dg[] dgField;

		private xp xpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("dg")]
		public dg[] dg
		{
			get
			{
				return this.dgField;
			}
			set
			{
				this.dgField = value;
			}
		}

		/// <remarks/>
		public xp xp
		{
			get
			{
				return this.xpField;
			}
			set
			{
				this.xpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class n
	{

		private string[] rField;

		private string[] textField;

		private eeliik_tyyp nrlField;

		private bool nrlFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("r")]
		public string[] r
		{
			get
			{
				return this.rField;
			}
			set
			{
				this.rField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public eeliik_tyyp nrl
		{
			get
			{
				return this.nrlField;
			}
			set
			{
				this.nrlField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool nrlSpecified
		{
			get
			{
				return this.nrlFieldSpecified;
			}
			set
			{
				this.nrlFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum eeliik_tyyp
	{

		/// <remarks/>
		var,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class nd
	{

		private string langField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class qn
	{

		private string[] xrField;

		private string[] textField;

		private string langField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("xr")]
		public string[] xr
		{
			get
			{
				return this.xrField;
			}
			set
			{
				this.xrField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class qng
	{

		private qn qnField;

		private v[] vField;

		private s[] sField;

		/// <remarks/>
		public qn qn
		{
			get
			{
				return this.qnField;
			}
			set
			{
				this.qnField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class qnp
	{

		private string[] rField;

		private v[] vField;

		private s[] sField;

		private nd[] ndField;

		private qng[] qngField;

		private string ntnrField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("r")]
		public string[] r
		{
			get
			{
				return this.rField;
			}
			set
			{
				this.rField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("nd")]
		public nd[] nd
		{
			get
			{
				return this.ndField;
			}
			set
			{
				this.ndField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("qng")]
		public qng[] qng
		{
			get
			{
				return this.qngField;
			}
			set
			{
				this.qngField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "positiveInteger")]
		public string ntnr
		{
			get
			{
				return this.ntnrField;
			}
			set
			{
				this.ntnrField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class ng
	{

		private n[] nField;

		private qnp[] qnpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("n")]
		public n[] n
		{
			get
			{
				return this.nField;
			}
			set
			{
				this.nField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("qnp")]
		public qnp[] qnp
		{
			get
			{
				return this.qnpField;
			}
			set
			{
				this.qnpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class np
	{

		private ng[] ngField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ng")]
		public ng[] ng
		{
			get
			{
				return this.ngField;
			}
			set
			{
				this.ngField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class tvt
	{

		private txhviiteliik_tyyp tvtlField;

		private string valueField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public txhviiteliik_tyyp tvtl
		{
			get
			{
				return this.tvtlField;
			}
			set
			{
				this.tvtlField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum txhviiteliik_tyyp
	{

		/// <remarks/>
		vt,

		/// <remarks/>
		vtka,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class tp
	{

		private string slField;

		private string rkField;

		private string gkiField;

		private tg[] tgField;

		private ng[] npField;

		private tvt[] tvtField;

		private string tnrField;

		/// <remarks/>
		public string sl
		{
			get
			{
				return this.slField;
			}
			set
			{
				this.slField = value;
			}
		}

		/// <remarks/>
		public string rk
		{
			get
			{
				return this.rkField;
			}
			set
			{
				this.rkField = value;
			}
		}

		/// <remarks/>
		public string gki
		{
			get
			{
				return this.gkiField;
			}
			set
			{
				this.gkiField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tg")]
		public tg[] tg
		{
			get
			{
				return this.tgField;
			}
			set
			{
				this.tgField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("ng", IsNullable = false)]
		public ng[] np
		{
			get
			{
				return this.npField;
			}
			set
			{
				this.npField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tvt")]
		public tvt[] tvt
		{
			get
			{
				return this.tvtField;
			}
			set
			{
				this.tvtField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "positiveInteger")]
		public string tnr
		{
			get
			{
				return this.tnrField;
			}
			set
			{
				this.tnrField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class S
	{

		private tp[] tpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("tp")]
		public tp[] tp
		{
			get
			{
				return this.tpField;
			}
			set
			{
				this.tpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class f
	{

		private string[] rField;

		private string[] textField;

		private frliik_tyyp frlField;

		private bool frlFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("r")]
		public string[] r
		{
			get
			{
				return this.rField;
			}
			set
			{
				this.rField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified)]
		public frliik_tyyp frl
		{
			get
			{
				return this.frlField;
			}
			set
			{
				this.frlField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool frlSpecified
		{
			get
			{
				return this.frlFieldSpecified;
			}
			set
			{
				this.frlFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.eki.ee/dict/schemas/evs_tyybid")]
	public enum frliik_tyyp
	{

		/// <remarks/>
		var,
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class qf
	{

		private string[] xrField;

		private string[] textField;

		private string langField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("xr")]
		public string[] xr
		{
			get
			{
				return this.xrField;
			}
			set
			{
				this.xrField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlTextAttribute()]
		public string[] Text
		{
			get
			{
				return this.textField;
			}
			set
			{
				this.textField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class fqng
	{

		private qf qfField;

		private v[] vField;

		private s[] sField;

		/// <remarks/>
		public qf qf
		{
			get
			{
				return this.qfField;
			}
			set
			{
				this.qfField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class fqnp
	{

		private string[] rField;

		private v[] vField;

		private s[] sField;

		private string[] fdField;

		private fqng[] fqngField;

		private string ftnrField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("r")]
		public string[] r
		{
			get
			{
				return this.rField;
			}
			set
			{
				this.rField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("v")]
		public v[] v
		{
			get
			{
				return this.vField;
			}
			set
			{
				this.vField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("s")]
		public s[] s
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("fd")]
		public string[] fd
		{
			get
			{
				return this.fdField;
			}
			set
			{
				this.fdField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("fqng")]
		public fqng[] fqng
		{
			get
			{
				return this.fqngField;
			}
			set
			{
				this.fqngField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, DataType = "positiveInteger")]
		public string ftnr
		{
			get
			{
				return this.ftnrField;
			}
			set
			{
				this.ftnrField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class fg
	{

		private f[] fField;

		private fqnp[] fqnpField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("f")]
		public f[] f
		{
			get
			{
				return this.fField;
			}
			set
			{
				this.fField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("fqnp")]
		public fqnp[] fqnp
		{
			get
			{
				return this.fqnpField;
			}
			set
			{
				this.fqnpField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class F
	{

		private fg[] fgField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("fg")]
		public fg[] fg
		{
			get
			{
				return this.fgField;
			}
			set
			{
				this.fgField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class A
	{

		private P pField;

		private tp[] sField;

		private fg[] fField;

		/// <remarks/>
		public P P
		{
			get
			{
				return this.pField;
			}
			set
			{
				this.pField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("tp", IsNullable = false)]
		public tp[] S
		{
			get
			{
				return this.sField;
			}
			set
			{
				this.sField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("fg", IsNullable = false)]
		public fg[] F
		{
			get
			{
				return this.fField;
			}
			set
			{
				this.fField = value;
			}
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.eki.ee/dict/evs")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.eki.ee/dict/evs", IsNullable = false)]
	public partial class sr
	{

		private A[] aField;

		private string langField;

		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("A")]
		public A[] A
		{
			get
			{
				return this.aField;
			}
			set
			{
				this.aField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
		public string lang
		{
			get
			{
				return this.langField;
			}
			set
			{
				this.langField = value;
			}
		}
	}

}
